name: Validation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: true

      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/go/bin
            /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Makefile') }}-lint
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Run lint (Makefile)
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: true

      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/go/bin
            /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Makefile') }}-test
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Run unit tests and coverage (Makefile)
        run: |
          make coverage

      - name: Upload codequality artifacts
        uses: actions/upload-artifact@v6
        with:
          name: codequality
          path: codequality/

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: docker.io/library/sonarqube:26.1.0.118079-community
        ports:
          - 9000:9000
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: true

      - name: Cache Go tools
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/go/bin
            /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-tools-${{ hashFiles('Makefile') }}-e2e
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Run E2E tests
        run: make e2e
